#include "codegen.h"
#include <cmath>
#include <iostream>
#include <stdexcept>
#include <cstdint>
  // Constructor
CodeGenerator::CodeGenerator()
    : labelCounter(0), stringCounter(0), currentFunction(nullptr),
      currentStackSize(0), inOverrideEval(false) {}
  // Label management
std::string CodeGenerator::newLabel(const std::string &prefix) {
  return ".L_" + prefix + "_" + std::to_string(labelCounter++);
}
  // String literal management
std::string CodeGenerator::addStringLiteral(const std::string &str) {
  auto it = stringLiterals.find(str);
  if (it != stringLiterals.end()) {
    return it->second;
  }
  std::string label = "str_" + std::to_string(stringCounter++);
  stringLiterals[str] = label;

  // Write to data section — escape special chars for NASM
  dataSection << "    " << label << " db ";

  bool first = true;
  std::string current;
  for (size_t i = 0; i < str.size(); i++) {
    char c = str[i];
    if (c == '\n' || c == '\t' || c == '\r' || c == '\0' || c == '"' ||
        (unsigned char)c < 32) {
      // Flush current printable segment
      if (!current.empty()) {
        if (!first)
          dataSection << ", ";
        dataSection << "\"" << current << "\"";
        current.clear();
        first = false;
      }
      if (!first)
        dataSection << ", ";
      dataSection << static_cast<int>((unsigned char)c);
      first = false;
    } else {
      current += c;
    }
  }
  if (!current.empty()) {
    if (!first)
      dataSection << ", ";
    dataSection << "\"" << current << "\"";
    first = false;
  }
  // null terminator
  if (!first)
    dataSection << ", ";
  dataSection << "0\n";

  return label;
}
  // Scope management
void CodeGenerator::pushScope() {
  Scope scope;
  if (scopes.empty()) {
    scope.nextOffset = -8; // first variable at [rbp-8]
  } else {
    scope.nextOffset = scopes.back().nextOffset;
  }
  scopes.push_back(scope);
}

void CodeGenerator::popScope() { scopes.pop_back(); }

CodeGenerator::VarInfo &
CodeGenerator::declareVar(const std::string &name, const std::string &type) {
  if (scopes.empty()) {
    throw std::runtime_error("No scope for variable declaration");
  }
  VarInfo info;
  info.stackOffset = scopes.back().nextOffset;
  info.type = type;
  scopes.back().nextOffset -= 8; // each var takes 8 bytes

  // Track total stack usage for function prologue
  int totalUsed = -(scopes.back().nextOffset + 8);
  if (totalUsed > currentStackSize)
    currentStackSize = totalUsed;

  scopes.back().vars[name] = info;
  return scopes.back().vars[name];
}

CodeGenerator::VarInfo *CodeGenerator::lookupVar(const std::string &name) {
  for (int i = static_cast<int>(scopes.size()) - 1; i >= 0; i--) {
    auto it = scopes[i].vars.find(name);
    if (it != scopes[i].vars.end()) {
      return &it->second;
    }
  }
  return nullptr;
}
  // Emission helpers
void CodeGenerator::emit(const std::string &line) {
  textSection << "    " << line << "\n";
}

void CodeGenerator::emitLabel(const std::string &label) {
  textSection << label << ":\n";
}

void CodeGenerator::emitComment(const std::string &comment) {
  textSection << "    ; " << comment << "\n";
}
  // Top-level: generate full NASM assembly
std::string CodeGenerator::generate(const Program &program) {
  genProgram(program);

  // Assemble the final output
  std::ostringstream out;

  out << "; ============================================\n";
  out << "; Chennai Lang — Compiled NASM x86-64 (Win64)\n";
  out << "; Generated by Chennai Lang Compiler v2.0\n";
  out << "; ============================================\n\n";

  out << "bits 64\n";
  out << "default rel\n\n";

  // Extern declarations
  out << "extern printf\n";
  out << "extern exit\n";
  out << "extern malloc\n";
  out << "extern free\n\n";

  // Data section
  out << "section .data\n";
  // Standard format strings
  out << "    fmt_int db \"%lld\", 0\n";
  out << "    fmt_str db \"%s\", 0\n";
  out << "    fmt_char db \"%c\", 0\n";
  out << "    fmt_float db \"%f\", 0\n";
  out << "    fmt_newline db 10, 0\n";
  out << dataSection.str();
  out << "\n";

  // BSS section
  out << "section .bss\n";
  out << bssSection.str();
  out << "\n";

  // Text section
  out << "section .text\n";
  out << "    global main\n\n";
  out << textSection.str();

  return out.str();
}
  // Program generation
void CodeGenerator::genProgram(const Program &program) {
  // Register operator overloads
  for (auto &ov : program.operators) {
    opOverrides[ov.op] = ov.body.get();
  }

  // Register all functions
  for (auto &fn : program.functions) {
    functions[fn->name] = fn.get();
  }

  // Generate code for each function
  for (auto &fn : program.functions) {
    genFunction(fn.get());
  }
}
  // Function generation
void CodeGenerator::genFunction(const FunctionDef *fn) {
  currentFunction = fn;
  currentStackSize = 0;

  // We need to pre-scan to determine stack size, but for simplicity
  // we'll use a fixed large allocation and adjust
  emitComment("Function: " + fn->name);
  emitLabel(fn->name);

  // Prologue
  emit("push rbp");
  emit("mov rbp, rsp");

  // We'll reserve space — placeholder, will be large enough
  // (256 bytes = 32 variables worth of space, plus shadow space)
  int stackReserve = 256;
  emit("sub rsp, " + std::to_string(stackReserve));

  pushScope();

  // Bind parameters — Windows x64 calling convention
  // First 4 integer/pointer args: RCX, RDX, R8, R9
  const std::string paramRegs[] = {"rcx", "rdx", "r8", "r9"};
  for (size_t i = 0; i < fn->params.size(); i++) {
    VarInfo &var = declareVar(fn->params[i].second, fn->params[i].first);
    if (i < 4) {
      emit("mov [rbp" + std::to_string(var.stackOffset) + "], " +
           paramRegs[i]);
    }
    // Args beyond 4 would be on the stack — we'll handle that if needed
  }

  // Generate body
  for (auto &stmt : fn->body->statements) {
    genStatement(stmt.get());
  }

  popScope();

  // Epilogue
  if (fn->name == "main") {
    emit("xor eax, eax"); // return 0
  }
  emit("mov rsp, rbp");
  emit("pop rbp");
  emit("ret");
  textSection << "\n";

  currentFunction = nullptr;
}
  // Block generation
void CodeGenerator::genBlock(const BlockStmt *block) {
  pushScope();
  for (auto &stmt : block->statements) {
    genStatement(stmt.get());
  }
  popScope();
}
  // Statement dispatch
void CodeGenerator::genStatement(const Stmt *stmt) {
  if (auto *s = dynamic_cast<const DeclarationStmt *>(stmt)) {
    genDeclaration(s);
  } else if (auto *s = dynamic_cast<const AssignmentStmt *>(stmt)) {
    genAssignment(s);
  } else if (auto *s = dynamic_cast<const ArrayAssignStmt *>(stmt)) {
    genArrayAssign(s);
  } else if (auto *s = dynamic_cast<const DeclAssignStmt *>(stmt)) {
    genDeclAssign(s);
  } else if (auto *s = dynamic_cast<const IfStmt *>(stmt)) {
    genIf(s);
  } else if (auto *s = dynamic_cast<const WhileStmt *>(stmt)) {
    genWhile(s);
  } else if (auto *s = dynamic_cast<const PrintStmt *>(stmt)) {
    genPrint(s);
  } else if (auto *s = dynamic_cast<const BlockStmt *>(stmt)) {
    genBlock(s);
  } else if (auto *s = dynamic_cast<const ExprStmt *>(stmt)) {
    genExprStmt(s);
  } else {
    throw std::runtime_error("CodeGen: Unknown statement type");
  }
}
  // Declaration: int x;
void CodeGenerator::genDeclaration(const DeclarationStmt *stmt) {
  emitComment("declare " + stmt->typeName + " " + stmt->varName);
  VarInfo &var = declareVar(stmt->varName, stmt->typeName);
  
  if (stmt->typeName.find("[]") != std::string::npos) {
    emitComment("allocate array (100 elements * 8 bytes)");
    emit("mov rcx, 800");
    emit("sub rsp, 32"); // shadow space
    emit("call malloc");
    emit("add rsp, 32");
    emit("mov qword [rbp" + std::to_string(var.stackOffset) + "], rax");
  } else {
    // Initialize to 0
    emit("mov qword [rbp" + std::to_string(var.stackOffset) + "], 0");
  }
}
  // Assignment: x = expr;
void CodeGenerator::genAssignment(const AssignmentStmt *stmt) {
  emitComment(stmt->varName + " = <expr>");
  genExpr(stmt->value.get());
  VarInfo *var = lookupVar(stmt->varName);
  if (!var) {
    throw std::runtime_error("CodeGen: Undefined variable: " + stmt->varName);
  }
  emit("mov [rbp" + std::to_string(var->stackOffset) + "], rax");
}
  // Array assignment: arr[idx] = expr;
void CodeGenerator::genArrayAssign(const ArrayAssignStmt *stmt) {
  emitComment(stmt->varName + "[idx] = <expr>");

  // Evaluate value → push onto stack
  genExpr(stmt->value.get());
  emit("push rax");

  // Evaluate index → RAX
  genExpr(stmt->index.get());
  emit("mov rcx, rax"); // index in rcx

  // Get array base pointer
  VarInfo *var = lookupVar(stmt->varName);
  if (!var) {
    throw std::runtime_error("CodeGen: Undefined variable: " + stmt->varName);
  }
  emit("mov rdx, [rbp" + std::to_string(var->stackOffset) + "]"); // base ptr

  // Pop value
  emit("pop rax");

  // Store: [base + index * 8] = value
  emit("mov [rdx + rcx * 8], rax");
}
  // Declaration + Assignment: int x = expr;
void CodeGenerator::genDeclAssign(const DeclAssignStmt *stmt) {
  emitComment("declare+assign " + stmt->typeName + " " + stmt->varName);
  VarInfo &var = declareVar(stmt->varName, stmt->typeName);
  genExpr(stmt->value.get());
  emit("mov [rbp" + std::to_string(var.stackOffset) + "], rax");
}
  // If / elif / else
void CodeGenerator::genIf(const IfStmt *stmt) {
  std::string endLabel = newLabel("endif");
  std::string elseLabel = newLabel("else");

  emitComment("if");

  // Evaluate condition
  genExpr(stmt->condition.get());
  emit("cmp rax, 0");
  if (stmt->elifs.empty() && !stmt->elseBlock) {
    emit("je " + endLabel);
  } else {
    emit("je " + elseLabel);
  }

  // Then block
  genBlock(dynamic_cast<const BlockStmt *>(stmt->thenBlock.get()));
  emit("jmp " + endLabel);

  // Elif chains
  for (size_t i = 0; i < stmt->elifs.size(); i++) {
    emitLabel(elseLabel);
    elseLabel = newLabel("else");

    emitComment("elif");
    genExpr(stmt->elifs[i].first.get());
    emit("cmp rax, 0");

    bool hasMore =
        (i + 1 < stmt->elifs.size()) || (stmt->elseBlock != nullptr);
    if (hasMore) {
      emit("je " + elseLabel);
    } else {
      emit("je " + endLabel);
    }

    genBlock(
        dynamic_cast<const BlockStmt *>(stmt->elifs[i].second.get()));
    emit("jmp " + endLabel);
  }

  // Else block
  if (stmt->elseBlock) {
    emitLabel(elseLabel);
    emitComment("else");
    genBlock(dynamic_cast<const BlockStmt *>(stmt->elseBlock.get()));
  } else if (!stmt->elifs.empty()) {
    // Need the final else label even if no else block
    emitLabel(elseLabel);
  }

  emitLabel(endLabel);
}
  // While loop
void CodeGenerator::genWhile(const WhileStmt *stmt) {
  std::string loopLabel = newLabel("while");
  std::string endLabel = newLabel("endwhile");

  emitComment("while");
  emitLabel(loopLabel);

  // Evaluate condition
  genExpr(stmt->condition.get());
  emit("cmp rax, 0");
  emit("je " + endLabel);

  // Body
  genBlock(dynamic_cast<const BlockStmt *>(stmt->body.get()));
  emit("jmp " + loopLabel);

  emitLabel(endLabel);
}
  // Print (sollu)
void CodeGenerator::genPrint(const PrintStmt *stmt) {
  emitComment("sollu (print)");

  for (auto &part : stmt->parts) {
    std::string type = inferExprType(part.get());

    if (type == "string") {
      // String expression — evaluate and print
      genExpr(part.get());
      // RAX has pointer to string
      emit("mov rdx, rax");       // arg2 = string
      emit("lea rcx, [fmt_str]"); // arg1 = format
      emit("sub rsp, 32");        // shadow space
      emit("call printf");
      emit("add rsp, 32");
    } else {
      // Numeric — evaluate and print as integer
      genExpr(part.get());
      emit("mov rdx, rax");       // arg2 = value
      emit("lea rcx, [fmt_int]"); // arg1 = format
      emit("sub rsp, 32");        // shadow space
      emit("call printf");
      emit("add rsp, 32");
    }
  }

  // Print newline
  emit("lea rcx, [fmt_newline]");
  emit("sub rsp, 32");
  emit("call printf");
  emit("add rsp, 32");
}
  // Expression statement (e.g. function call)
void CodeGenerator::genExprStmt(const ExprStmt *stmt) {
  genExpr(stmt->expr.get());
}
  // Expression generation — result always in RAX
void CodeGenerator::genExpr(const Expr *expr) {
  if (auto *e = dynamic_cast<const NumberExpr *>(expr)) {
    emit("mov rax, " + std::to_string(e->value));
    return;
  }

  if (auto *e = dynamic_cast<const FloatExpr *>(expr)) {
    // Store float as integer representation for now
    // (proper float support would use SSE/XMM registers)
    int64_t intVal = static_cast<int64_t>(e->value);
    emit("mov rax, " + std::to_string(intVal));
    return;
  }

  if (auto *e = dynamic_cast<const CharExpr *>(expr)) {
    emit("mov rax, " + std::to_string(static_cast<int>(e->value)));
    return;
  }

  if (auto *e = dynamic_cast<const StringExpr *>(expr)) {
    std::string label = addStringLiteral(e->value);
    emit("lea rax, [" + label + "]");
    return;
  }

  if (auto *e = dynamic_cast<const IdentifierExpr *>(expr)) {
    VarInfo *var = lookupVar(e->name);
    if (!var) {
      throw std::runtime_error("CodeGen: Undefined variable: " + e->name);
    }
    emit("mov rax, [rbp" + std::to_string(var->stackOffset) + "]");
    return;
  }

  if (auto *e = dynamic_cast<const BinaryExpr *>(expr)) {
    genBinary(e);
    return;
  }

  if (auto *e = dynamic_cast<const UnaryExpr *>(expr)) {
    genUnary(e);
    return;
  }

  if (auto *e = dynamic_cast<const CallExpr *>(expr)) {
    genCall(e);
    return;
  }

  if (auto *e = dynamic_cast<const ArrayAccessExpr *>(expr)) {
    genArrayAccess(e);
    return;
  }

  if (auto *e = dynamic_cast<const AssignExpr *>(expr)) {
    genExpr(e->value.get());
    VarInfo *var = lookupVar(e->name);
    if (!var)
      throw std::runtime_error("CodeGen: Undefined variable: " + e->name);
    emit("mov [rbp" + std::to_string(var->stackOffset) + "], rax");
    return;
  }

  throw std::runtime_error("CodeGen: Unknown expression type");
}
  // Binary expression
void CodeGenerator::genBinary(const BinaryExpr *expr) {
  // Check for operator override (inline expansion)
  // Guard with inOverrideEval to prevent infinite recursion
  if (!inOverrideEval) {
    auto ovIt = opOverrides.find(expr->op);
    if (ovIt != opOverrides.end()) {
      // To inline operator overloads:
      // 1. Evaluate LHS → save to temp
      // 2. Evaluate RHS → save to temp
      // 3. Set __LHS__ and __RHS__ variables
      // 4. Generate the override expression body
      emitComment("operator override: " + expr->op);

      genExpr(expr->lhs.get());
      emit("push rax"); // save LHS

      genExpr(expr->rhs.get());
      emit("push rax"); // save RHS

      // Declare __LHS__ and __RHS__ in a new scope
      pushScope();
      VarInfo &lhsVar = declareVar("__LHS__", "int");
      VarInfo &rhsVar = declareVar("__RHS__", "int");

      emit("pop rax");
      emit("mov [rbp" + std::to_string(rhsVar.stackOffset) + "], rax");
      emit("pop rax");
      emit("mov [rbp" + std::to_string(lhsVar.stackOffset) + "], rax");

      // Generate override body — set guard to prevent re-entry
      inOverrideEval = true;
      genExpr(ovIt->second);
      inOverrideEval = false;

      popScope();
      return;
    }
  }

  // String concatenation with + is special — handled at print level
  // For compiled code, string concat needs runtime support (skipped for v1)

  // Evaluate LHS
  genExpr(expr->lhs.get());
  emit("push rax");

  // Evaluate RHS
  genExpr(expr->rhs.get());
  emit("mov rbx, rax"); // RHS in rbx

  emit("pop rax"); // LHS in rax

  // Arithmetic operations
  if (expr->op == "+") {
    emit("add rax, rbx");
  } else if (expr->op == "-") {
    emit("sub rax, rbx");
  } else if (expr->op == "*") {
    emit("imul rax, rbx");
  } else if (expr->op == "/") {
    emit("cqo");        // sign-extend RAX into RDX:RAX
    emit("idiv rbx");   // result in RAX, remainder in RDX
  } else if (expr->op == "%") {
    emit("cqo");
    emit("idiv rbx");
    emit("mov rax, rdx"); // remainder
  } else if (expr->op == "^") {
    // Power — use a loop for integer power
    // rax = base, rbx = exponent
    std::string loopLabel = newLabel("pow");
    std::string endLabel = newLabel("endpow");
    emit("mov rcx, rbx");   // exponent in rcx
    emit("mov rbx, rax");   // base in rbx
    emit("mov rax, 1");     // result = 1
    emitLabel(loopLabel);
    emit("cmp rcx, 0");
    emit("jle " + endLabel);
    emit("imul rax, rbx");  // result *= base
    emit("dec rcx");
    emit("jmp " + loopLabel);
    emitLabel(endLabel);
  }
  // Comparison operations — result is 0 or 1 in RAX
  else if (expr->op == "<") {
    emit("cmp rax, rbx");
    emit("setl al");
    emit("movzx rax, al");
  } else if (expr->op == ">") {
    emit("cmp rax, rbx");
    emit("setg al");
    emit("movzx rax, al");
  } else if (expr->op == "<=") {
    emit("cmp rax, rbx");
    emit("setle al");
    emit("movzx rax, al");
  } else if (expr->op == ">=") {
    emit("cmp rax, rbx");
    emit("setge al");
    emit("movzx rax, al");
  } else if (expr->op == "==") {
    emit("cmp rax, rbx");
    emit("sete al");
    emit("movzx rax, al");
  } else if (expr->op == "!=") {
    emit("cmp rax, rbx");
    emit("setne al");
    emit("movzx rax, al");
  }
  // Logical operations
  else if (expr->op == "&&") {
    // Short-circuit AND
    std::string falseLabel = newLabel("and_false");
    std::string endLabel = newLabel("and_end");
    emit("cmp rax, 0");
    emit("je " + falseLabel);
    emit("cmp rbx, 0");
    emit("je " + falseLabel);
    emit("mov rax, 1");
    emit("jmp " + endLabel);
    emitLabel(falseLabel);
    emit("mov rax, 0");
    emitLabel(endLabel);
  } else if (expr->op == "||") {
    // Short-circuit OR
    std::string trueLabel = newLabel("or_true");
    std::string endLabel = newLabel("or_end");
    emit("cmp rax, 0");
    emit("jne " + trueLabel);
    emit("cmp rbx, 0");
    emit("jne " + trueLabel);
    emit("mov rax, 0");
    emit("jmp " + endLabel);
    emitLabel(trueLabel);
    emit("mov rax, 1");
    emitLabel(endLabel);
  } else {
    throw std::runtime_error("CodeGen: Unknown binary operator: " + expr->op);
  }
}
  // Unary expression
void CodeGenerator::genUnary(const UnaryExpr *expr) {
  genExpr(expr->operand.get());
  if (expr->op == "-") {
    emit("neg rax");
  } else if (expr->op == "!") {
    emit("cmp rax, 0");
    emit("sete al");
    emit("movzx rax, al");
  } else {
    throw std::runtime_error("CodeGen: Unknown unary operator: " + expr->op);
  }
}
  // Function call
void CodeGenerator::genCall(const CallExpr *expr) {
  emitComment("call " + expr->callee);

  // Evaluate arguments (up to 4 in registers, rest on stack)
  const std::string paramRegs[] = {"rcx", "rdx", "r8", "r9"};

  // Evaluate args in reverse order onto stack, then pop into registers
  for (int i = static_cast<int>(expr->args.size()) - 1; i >= 0; i--) {
    genExpr(expr->args[i].get());
    emit("push rax");
  }

  // Pop into parameter registers
  for (size_t i = 0; i < expr->args.size() && i < 4; i++) {
    emit("pop " + paramRegs[i]);
  }

  // Shadow space (32 bytes required by Windows x64 ABI)
  emit("sub rsp, 32");
  emit("call " + expr->callee);
  emit("add rsp, 32");

  // Clean up stack args beyond 4 if any
  if (expr->args.size() > 4) {
    int extraArgs = static_cast<int>(expr->args.size()) - 4;
    emit("add rsp, " + std::to_string(extraArgs * 8));
  }
}
  // Array access
void CodeGenerator::genArrayAccess(const ArrayAccessExpr *expr) {
  emitComment("array access: " + expr->name + "[idx]");

  // Evaluate index → RAX
  genExpr(expr->index.get());
  emit("mov rcx, rax"); // index in rcx

  // Get array base pointer
  VarInfo *var = lookupVar(expr->name);
  if (!var) {
    throw std::runtime_error("CodeGen: Undefined variable: " + expr->name);
  }
  emit("mov rdx, [rbp" + std::to_string(var->stackOffset) + "]"); // base ptr
  emit("mov rax, [rdx + rcx * 8]");                                // load element
}
  // Type inference (simple heuristic for print formatting)
std::string CodeGenerator::inferExprType(const Expr *expr) {
  if (dynamic_cast<const StringExpr *>(expr))
    return "string";
  if (dynamic_cast<const NumberExpr *>(expr))
    return "int";
  if (dynamic_cast<const FloatExpr *>(expr))
    return "float";
  if (dynamic_cast<const CharExpr *>(expr))
    return "char";

  if (auto *e = dynamic_cast<const IdentifierExpr *>(expr)) {
    VarInfo *var = lookupVar(e->name);
    if (var)
      return var->type;
  }

  if (auto *e = dynamic_cast<const BinaryExpr *>(expr)) {
    if (e->op == "+") {
      std::string ltype = inferExprType(e->lhs.get());
      std::string rtype = inferExprType(e->rhs.get());
      if (ltype == "string" || rtype == "string")
        return "string";
    }
    return "int"; // default for arithmetic
  }

  if (dynamic_cast<const CallExpr *>(expr))
    return "int";
  if (dynamic_cast<const ArrayAccessExpr *>(expr))
    return "int";

  return "int"; // default
}
